apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  generation: 2
  labels:
    app: go-web-redis
  name: go-web-redis
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: go-web-redis
    deploymentconfig: go-web-redis
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: go-web-redis
        deploymentconfig: go-web-redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redis-server
        ports:
        - containerPort: 6379
          protocol: TCP
      - image: m7dock/go-web-redis
        imagePullPolicy: Always
        name: go-web-redis
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - go-web-redis
      from:
        kind: ImageStreamTag
        name: go-web-redis:latest
    type: ImageChange
