apiVersion: v1
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: go-app
      name: go-app
    spec:
      replicas: 1
      selector:
        app: go-app
        deploymentconfig: go-app
      strategy:
        resources: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: go-app
            deploymentconfig: go-app
        spec:
          containers:
            - image: m7dock/go-app
              name: go-app
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              volumeMounts:
                - name: be-kind
                  mountPath: /data
          volumes:
            - name: be-kind
              persistentVolumeClaim:
                claimName: claim-2b-nice
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - go-app
            from:
              kind: ImageStreamTag
              name: go-app:latest
          type: ImageChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
  # - apiVersion: v1
  #   kind: PersistentVolumeClaim
  #   metadata:
  #     name: claim-2b-nice
  #   spec:
  #     accessModes:
  #       - ReadWriteMany
  #     storageClassName: local-ssd
  #     resources:
  #       requests:
  #         storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: claim-2b-nice
    spec:
      capacity:
        storage: 2Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: local-ssd
      local:
        path: /mnt/local-storage/ssd
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - aplrbocpnd001.sempra.com
                    - aplrbocpnd002.sempra.com
                    - aplrbocpnd003.sempra.com
                    - aplrbocpnd004.sempra.com
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: go-app
      name: go-app
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: go-app
        deploymentconfig: go-app
    status:
      loadBalancer: {}
kind: List
metadata: {}
